apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zs5cqbzst-nodejs
  janus-idp.io/tekton: zs5cqbzst-nodejs
  backstage.io/kubernetes-id: zs5cqbzst-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zs5cqbzst-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
