apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zs5cqbzst-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zs5cqbzst-nodejs 
  name: zs5cqbzst-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: zs5cqbzst-nodejs 
